{{- if and .Values.postgres.internal (.Capabilities.APIVersions.Has "security.istio.io/v1beta1") }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: postgres-peerauthentication-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
  selector:
    matchLabels:
      {{ .Values.postgres.selector }}
  portLevelMtls:
    # Postgres exception to support GitLab dependency init containers
    {{ .Values.postgres.port }}:
      mode: PERMISSIVE
{{- end }}
