{{- if and .Values.redis.internal (.Capabilities.APIVersions.Has "security.istio.io/v1beta1") }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: redis-peerauthentication-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
  selector:
    matchLabels:
      {{ .Values.redis.selector }}
  portLevelMtls:
    # Redis/Valkey exception to support GitLab dependency init containers
    {{ .Values.redis.port }}:
      mode: PERMISSIVE
{{- end }}
