variables:
  - name: FLAVOR
    default: "registry1"

tasks:
  - name: gitlab-test-bundle
    description: Create the UDS bundle with Gitlab and its dependencies
    actions:
      - task: gitlab-package
      - task: dependency-package
      - cmd: uds create bundle --confirm --no-progress --architecture=${UDS_ARCH}

  - name: gitlab-package
    description: Create the UDS Gitlab Zarf Package
    actions:
      - cmd: uds zarf package create --confirm --no-progress --architecture=${ZARF_ARCHITECTURE} --flavor ${FLAVOR}

  - name: dependency-package
    description: Create the Minio, PostgreSQL, and Redis Dependency Zarf Packages
    actions:
      - cmd: uds zarf package create src/dev-secrets/ --confirm --no-progress --architecture=${UDS_ARCH} --skip-sbom
