# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if .Values.botAccounts.enabled }}
{{- range .Values.botAccounts.accounts }}
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .secret.namespace }}
---
{{- end }}
{{- end }}
