{{- if .Values.settingsJob.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-settings-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-settings-role
  namespace: {{ .Release.Namespace }}
rules:
  # Only allow exec into the toolbox pod
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
    resourceNames:
      - gitlab-toolbox
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-settings-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: gitlab-settings-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: gitlab-settings-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
