# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: gitlab-postgres-peerauthentication-shim-exception
  namespace: postgres
spec:
  mtls:
    mode: STRICT
  selector:
    matchLabels:
      cluster-name: pg-cluster
  portLevelMtls:
    # Postgres exception to support GitLab dependency init containers
    5432:
      mode: PERMISSIVE
