apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: gitlab-redis-peerauthentication-shim-exception
  namespace: valkey
spec:
  mtls:
    mode: STRICT
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey
  portLevelMtls:
    # Redis/Valkey exception to support GitLab dependency init containers
    6379:
      mode: PERMISSIVE
