# This secret will be used if sso is disabled, instead of the templated one in uds-package.yaml. 
# GitLab needs to mount the secret and creating it this way avoids creating an unnecessary 
# client in the keycloak realm and unnecessary secret data in the cluster.
{{- if not .Values.sso.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sso.secretName }}
  namespace:  {{ .Release.Namespace }}
type: "Opaque"
stringData:
  providers: |
    {
      "name": "openid_connect",
      "label": "Dummy SSO",
      "args": {
        "name": "openid_connect",
        "scope": [
          "openid",
          "profile"
        ],
        "response_type": "code",
        "issuer": "https://sso.{{ .Values.domain }}/realms/uds",
        "client_auth_method": "query",
        "discovery": true,
        "uid_field": "preferred_username",
        "client_options": {
          "identifier": "dummy_identifier",
          "secret": "dummy_secret",
          "redirect_uri": "https://dummy_redirect_uri.com",
          "end_session_endpoint": "https://dummy_end_session_endpoint.com"
        }
      }
    }
{{- end }}
