# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if ne .Values.postgres.password "" }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-postgres
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/opaque
stringData:
  password: {{ .Values.postgres.password }}
{{- end }}
