# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if and .Values.redis.internal (.Capabilities.APIVersions.Has "security.istio.io/v1beta1") }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: gitlab-redis-peerauthentication-exception
  namespace: {{ .Values.redis.namespace }}
spec:
  mtls:
    mode: STRICT
  selector:
    matchLabels:
      {{ .Values.redis.selector | toYaml }}
  portLevelMtls:
    # Redis/Valkey exception to support GitLab 'dependency' init containers
    {{ .Values.redis.port }}:
      mode: PERMISSIVE
    {{- if .Values.redis.sentinel.enabled }}
    {{ .Values.redis.sentinel.port }}:
      mode: PERMISSIVE
    {{- end }}
{{- end }}
