# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

{{- if ne .Values.redis.password "" }}
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-redis
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/opaque
stringData:
  password: {{ .Values.redis.password }}
{{- end }}
