# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Lint

on:
  # This workflow is triggered on pull requests to the main branch.
  pull_request:
    # milestoned is added here as a way to retrigger workflows that are stuck or otherwise didn't run correctly
    types: [milestoned, opened, reopened, synchronize]

# Permissions for the GITHUB_TOKEN used by the workflow.
permissions:
  contents: read # Allows reading the content of the repository.

jobs:
  validate:
    uses: defenseunicorns/uds-common/.github/workflows/callable-lint.yaml@e416744c8c170e73e2bc5e8b0020afa171a2bfe2 # v1.17.1
    secrets: inherit
